#!/usr/bin/env bash

# PTB Normal
#python -u run_all.py --data dataset/ptb/.full --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path ptb_full
#python -u run_all.py --data dataset/ptb/.train --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path ptb_train
#python -u run_all.py --data dataset/ptb/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path ptb_test
#python -u run_all.py --data dataset/ptb/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path ptb_valid

# Wiki2 Normal
#python -u run_all.py --data dataset/wiki2/.full --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2_full
#python -u run_all.py --data dataset/wiki2/.train --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2_train
#python -u run_all.py --data dataset/wiki2/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2_test
#python -u run_all.py --data dataset/wiki2/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2_valid

# Wiki2 Raw
#python -u run_all.py --data dataset/wiki2R/.full --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2R_full
#python -u run_all.py --data dataset/wiki2R/.train --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2R_train
#python -u run_all.py --data dataset/wiki2R/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2R_test
#python -u run_all.py --data dataset/wiki2R/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2R_valid

# Wiki2 Cleaned (all)
#python -u run_all.py --data dataset/wiki2C/.full --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2C_full
#python -u run_all.py --data dataset/wiki2C/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2C_test
#python -u run_all.py --data dataset/wiki2C/.train --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2C_train
#python -u run_all.py --data dataset/wiki2C/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2C_valid

# Wiki2 Modified (New)
#python -u run_all.py --data dataset/wiki2M/.test1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2M_test1
#python -u run_all.py --data dataset/wiki2M/.test2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2M_test2
#python -u run_all.py --data dataset/wiki2M/.valid1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2M_valid1
#python -u run_all.py --data dataset/wiki2C/.test1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2MC_test1
#python -u run_all.py --data dataset/wiki2C/.test2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2MC_test2
#python -u run_all.py --data dataset/wiki2C/.valid1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2MC_valid1

# Wiki2 Samples
#python -u run_all.py --data dataset/wiki2Samples/.full1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples1_full
#python -u run_all.py --data dataset/wiki2Samples/.full2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples2_full
#python -u run_all.py --data dataset/wiki2Samples/.full3 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples3_full
#python -u run_all.py --data dataset/wiki2Samples/.full4 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples4_full
#python -u run_all.py --data dataset/wiki2Samples/.test1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples1_test
#python -u run_all.py --data dataset/wiki2Samples/.test2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples2_test
#python -u run_all.py --data dataset/wiki2Samples/.test3 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples3_test
#python -u run_all.py --data dataset/wiki2Samples/.test4 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples4_test
#python -u run_all.py --data dataset/wiki2Samples/.train1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples1_train
#python -u run_all.py --data dataset/wiki2Samples/.train2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples2_train
#python -u run_all.py --data dataset/wiki2Samples/.train3 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples3_train
#python -u run_all.py --data dataset/wiki2Samples/.train4 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples4_train
#python -u run_all.py --data dataset/wiki2Samples/.valid1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples1_valid
#python -u run_all.py --data dataset/wiki2Samples/.valid2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples2_valid
#python -u run_all.py --data dataset/wiki2Samples/.valid3 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples3_valid
#python -u run_all.py --data dataset/wiki2Samples/.valid4 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Samples4_valid

# Wiki2 Resampled
#python -u run_all.py --data dataset/wiki2Resample/.full1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample1_full
#python -u run_all.py --data dataset/wiki2Resample/.full2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample2_full
#python -u run_all.py --data dataset/wiki2Resample/.full3 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample3_full
#python -u run_all.py --data dataset/wiki2Resample/.full4 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample4_full
#python -u run_all.py --data dataset/wiki2Resample/.test1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample1_test
#python -u run_all.py --data dataset/wiki2Resample/.test2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample2_test
#python -u run_all.py --data dataset/wiki2Resample/.test3 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample3_test
#python -u run_all.py --data dataset/wiki2Resample/.test4 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample4_test
#python -u run_all.py --data dataset/wiki2Resample/.train1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample1_train
#python -u run_all.py --data dataset/wiki2Resample/.train2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample2_train
#python -u run_all.py --data dataset/wiki2Resample/.train3 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample3_train
#python -u run_all.py --data dataset/wiki2Resample/.train4 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample4_train
#python -u run_all.py --data dataset/wiki2Resample/.valid1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample1_valid
#python -u run_all.py --data dataset/wiki2Resample/.valid2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample2_valid
#python -u run_all.py --data dataset/wiki2Resample/.valid3 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample3_valid
#python -u run_all.py --data dataset/wiki2Resample/.valid4 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2Resample4_valid

# Wiki New Homogenous
#python -u run_all.py --data dataset/wiki2Homogenous/.fullH1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousH!_full
#python -u run_all.py --data dataset/wiki2Homogenous/.fullH2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousH2_full
#python -u run_all.py --data dataset/wiki2Homogenous/.fullCH1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousCH1_full
#python -u run_all.py --data dataset/wiki2Homogenous/.fullCH2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousCH2_full
#python -u run_all.py --data dataset/wiki2Homogenous/.testH1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousH1_test
#python -u run_all.py --data dataset/wiki2Homogenous/.testH2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousH2_test
#python -u run_all.py --data dataset/wiki2Homogenous/.testCH1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousCH1_test
#python -u run_all.py --data dataset/wiki2Homogenous/.testCH2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousCH2_test
#python -u run_all.py --data dataset/wiki2Homogenous/.trainH1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousH1_train
#python -u run_all.py --data dataset/wiki2Homogenous/.trainH2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousH2_train
#python -u run_all.py --data dataset/wiki2Homogenous/.trainCH1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousCH1_train
#python -u run_all.py --data dataset/wiki2Homogenous/.trainCH2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousCH2_train
#python -u run_all.py --data dataset/wiki2Homogenous/.validH1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousH1_valid
#python -u run_all.py --data dataset/wiki2Homogenous/.validH2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousH2_valid
#python -u run_all.py --data dataset/wiki2Homogenous/.validCH1 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousCH1_valid
#python -u run_all.py --data dataset/wiki2Homogenous/.validCH2 --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki2HomogenousCH2_valid

# Text8 Small
#python -u run_all.py --data dataset/hutter/text8w_small/.full --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path text8w_small_full
#python -u run_all.py --data dataset/hutter/text8w_small/.train --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path text8w_small_train
#python -u run_all.py --data dataset/hutter/text8w_small/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path text8w_small_test
#python -u run_all.py --data dataset/hutter/text8w_small/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path text8w_small_valid

# Text8
#python -u run_all.py --data dataset/hutter/text8w/.full --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path text8w_full
#python -u run_all.py --data dataset/hutter/text8w/.train --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path text8w_train
#python -u run_all.py --data dataset/hutter/text8w/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path text8w_test
#python -u run_all.py --data dataset/hutter/text8w/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path text8w_valid

# Wiki19 Normal
#python -u run_all.py --data dataset/wiki19/.full --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19_full
#python -u run_all.py --data dataset/wiki19/.train --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19_train
#python -u run_all.py --data dataset/wiki19/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19_test
#python -u run_all.py --data dataset/wiki19/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19_valid

# Wiki19 Cleaned
#python -u run_all.py --data dataset/wiki19C/.full --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19C_full
#python -u run_all.py --data dataset/wiki19C/.train --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19C_train
#python -u run_all.py --data dataset/wiki19C/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19C_test
#python -u run_all.py --data dataset/wiki19C/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19C_valid

# Wiki19 Text8 Like
#python -u run_all.py --data dataset/wiki19L/.full --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19L_full
#python -u run_all.py --data dataset/wiki19L/.train --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19L_train
#python -u run_all.py --data dataset/wiki19L/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19L_test
#python -u run_all.py --data dataset/wiki19L/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19L_valid

# Wiki19 Text8 Like - WOR
#python -u run_all.py --data dataset/wiki19L-wor/.full --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19Lwor_full
#python -u run_all.py --data dataset/wiki19L-wor/.train --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19Lwor_train
#python -u run_all.py --data dataset/wiki19L-wor/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19Lwor_test
#python -u run_all.py --data dataset/wiki19L-wor/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki19Lwor_valid

# Wiki103
#python -u run_all.py --data dataset/wiki103/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki103_test
#python -u run_all.py --data dataset/wiki103/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki103_valid

# Wiki103 Cleaned
#python -u run_all.py --data dataset/wiki103C/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki103C_test
#python -u run_all.py --data dataset/wiki103C/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki103C_valid

# Wiki103 Raw
#python -u run_all.py --data dataset/wiki103R/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki103R_test
#python -u run_all.py --data dataset/wiki103R/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki103R_valid


#python -u run_all.py --data dataset/wiki103/.train --words 1 --threads 5 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki103_train
#python -u run_all.py --data dataset/wiki103C/.train --words 1 --threads 1 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 0 --save_path wiki103C_train
#python -u run_all.py --data dataset/wiki103R/.train --words 1 --threads 5 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path wiki103R_train


#python -u run_all.py --data dataset/ptb_text8/.full --words 1 --threads 5 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path ptb_text8_full
#python -u run_all.py --data dataset/ptb_text8/.train --words 1 --threads 5 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path ptb_text8_train
#python -u run_all.py --data dataset/ptb_text8/.test --words 1 --threads 5 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path ptb_text8_test
#python -u run_all.py --data dataset/ptb_text8/.valid --words 1 --threads 5 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path ptb_text8_valid


#python -u run_all.py --data dataset/hutter/text8w_S/.test --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path text8w_S_test
#python -u run_all.py --data dataset/hutter/text8w_S/.valid --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path text8w_S_valid
#python -u run_all.py --data dataset/hutter/text8w_S/.train --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 1 --save_path text8w_S_train
#python -u run_all.py --data dataset/hutter/text8w_S/.full --words 1 --threads 10 --log_type 0 --mi_method grassberger --overlap 1 --cutoff 10000 --clear 0 --save_path text8w_S_full
